[main]
#Whether the variable names should be obfuscated
obfuscate = true
#Enable (experimental and unchecked) JS support
js = false
#Filler when EOF is reached
filler = "why is github ignoring .gitignore "

[files]
#Code file
code="code.txt"
#Shape file
shape="shape.txt"
#Output file
output="output.txt"
#In case you need a reminder, this is a program that not only obfuscates code,
#but causes the code's shape to fit to the shape.txt file.
#I must warn you that the program does not check if your program is too large to fit,
#it will simply truncate your code and stop.